import Head from 'next/head'
import Image from 'next/future/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/beach_huts.jpg" priority width={712} height={457} />

        <Image src="/beach_huts.jpg" width={712} height={457} />
      </main>

      <footer className={styles.footer} />
    </div>
  )
}
